services:
  python:
    build: ./python
    restart: always
    container_name: python
    volumes:
      - ./notebooks/:/root/notebooks
    ports:
      - "1234:1234"
      - "8501:8501"
    environment:
      - JUPYTER_TOKEN=dlinano
    command: jupyter lab --no-browser --ip=0.0.0.0 --port=1234 --allow-root
    networks:
      - dev-network

  ollama:
    build: ./ollama
    restart: always
    container_name: ollama
    ports:
      - "11434:11434" # Default port for Ollama
    volumes:
      - ./ollama_model:/root/.ollama
    networks:
      - dev-network

networks:
  dev-network:
    name: dev-network
    driver: bridge